### ISSUE TITLE
Post on speedups to TruffleMumbler

### ISSUE THREAD

**Issue by cesquivias** [cesquivias/cesquivias.github.io#1]
With the help of [Christian](https://github.com/Grashalm) and [Stefan](https://github.com/smarr) I've improved the speed of the TruffleMumbler implementation. Write up steps and speed improvements.

**Comment by jiridanek** [comment]
I think the way you did your measurements in the blog was unfair towards Truffle. The first time something is evaluated, it is slower than subsequent evaluations. With that in mind, you could've first run the benchmarked program say five times to give the machinery some time to warm up and only then do the timed run.

**Comment by cesquivias** [comment]
Christian pointed out the same thing. My follow-up post will mentioned that and show some updated numbers.

**Comment by cesquivias** [comment]
http://cesquivias.github.io/blog/2015/01/08/writing-a-language-in-truffle-part-3-making-my-language-much-faster/
